parties: # parties default id
  guest:
    - 10000
  host:
    - 10001
  arbiter:
    - 9999

work_mode: 0 # 0 for standalone, or 1 for cluster

data_base_dir: "/home/lupo/Development/Software/Github/eliaskousk/fate/FATE" # path to project base where data is located
